### PR TITLE
Overhaul

### LINKED ISSUE #13: Method on DESCRIBE-OBJECT :AFTER on SYMBOL invokes UB
https://github.com/guicho271828/lisp-namespace/blob/f006ee0b617f2eef0d33a08a5a77497b8fca33a2/src/namespace.lisp#L17

As useful as this method is, this isn't portable code - it violates [CLHS 11.1.2.1.2.19](http://www.lispworks.com/documentation/lw71/CLHS/Body/11_abab.htm) and therefore invokes undefined behavior:

>  Except where explicitly allowed, the consequences are undefined if any of the following actions are performed on an external symbol of the COMMON-LISP package: 
> ...
> 19. Defining a method for a standardized generic function which is applicable when all of the arguments are direct instances of standardized classes. 

We'll need to look at something implementation-defined in order to get something that's not effectively UB.

### LINKED ISSUE #14: Handle CLISP and LispWorks properly
There are workarounds for these two implementations:

https://github.com/guicho271828/lisp-namespace/blob/28107cafe34e4c1c67490fde60c7f92dc610b2e0/src/namespace.lisp#L11-L14

It does not seem that either of these implementations supply their own `:AFTER` method for `DESCRIBE-OBJECT SYMBOL T`; they only have package locking. In particular:

## CLISP 2.49.93+

```lisp
[1]> (ext:without-package-lock ("COMMON-LISP") (defmethod describe-object :after ((o symbol) stream) (print "hahaha" stream)))
#<STANDARD-METHOD :AFTER (#<BUILT-IN-CLASS SYMBOL> #<BUILT-IN-CLASS T>)>
[2]> (describe 'foo)

FOO is the symbol FOO, lies in #<PACKAGE COMMON-LISP-USER>, is accessible in 1 package COMMON-LISP-USER.

 #<PACKAGE COMMON-LISP-USER> is the package named COMMON-LISP-USER. It has 2 nicknames CL-USER, USER.
 It imports the external symbols of 2 packages COMMON-LISP, EXT and exports no symbols, but no package uses these
 exports.

"hahaha"
```

## LispWorks 7.1.2 Personal

```lisp
CL-USER 4 > (let ((lispworks:*handle-warn-on-redefinition* nil)) (defmethod describe-object :after ((o symbol) stream) (print "hahaha" stream)))
#<STANDARD-METHOD DESCRIBE-OBJECT (:AFTER) (SYMBOL T) 4020158D5B>

CL-USER 5 > (describe 'foo)

FOO is a SYMBOL
NAME          "FOO"
VALUE         #<unbound value>
FUNCTION      #<unbound function>
PLIST         NIL
PACKAGE       #<The COMMON-LISP-USER package, 5/16 internal, 0/4 external>
"hahaha" 
```

### PR DESCRIPTION
**Pull request by phoe**
This is a WIP attempt at overhauling the code of `LISP-NAMESPACE`.

Changes:

* Refactor the code,
* Export accessors for accessing namespaces,
* Fix adding the `PRINT-OBJECT` method for CLISP and Lispworks (closes #14),
* Document the `PRINT-OBJECT` kludge and add a safeguard against overwriting an already existing method (closes #13),
* Add tests for all accessors for:
  * the standard namespace,
  * a custom namespace.

Backwards-incompatible changes:

* Remove `NAMESPACE-LET` and `NSLET` altogether because:
  * symbols `LISPN:MACRO`, `LISPN:LABEL`, `LISPN:SYMBOL-MACRO` were not exported,
  * there were no tests for their functionality,
  * based on the fact that no one noticed the above two, they might not have any users.
* Move the locations of hash tables:
  * remove implicitly created hash-table variables
  * store hash tables in the namespace structure instead:
  * add accessors `NAMESPACE-HASH-TABLE` and `NAMESPACE-DOCUMENTATION-TABLE` for accessing binding and documentation hash tables

TODO:

* [x] long form of `DEFINE-NAMESPACE` for further customization
  * [x] customize generated names
  * [x] customize hash table tests, e.g. for namespaces which should be named via strings)
* [ ] Update README

Is this something that could be merged into this repository, or are the changes too incompatible and should I fork the project instead?

### CODE REVIEW

**Comment by phoe** [comment]
The Travis job at https://app.travis-ci.com/github/phoe-trash/lisp-namespace/builds/245581877 seems to build with SBCL, CCL, ECL, CMUCL, and CLISP, which is kinda good enough for me.

ABCL failed to download because of https://github.com/roswell/roswell/issues/509 and ACL has an error, `"(FUNCTION (SYMBOL &OPTIONAL (OR NULL LISP-NAMESPACE:NAMESPACE-TYPE)) (:DEFAULT)) is not a valid type specifier"`, that I can't debug at the moment because I don't have an ACL setup.

**Comment by phoe** [comment]
Ayup, my changes resulted in too much backwards incompatibility - I've ended up making a whole new piece of software instead (https://github.com/phoe/in-nomine). Closing the PR.

**Comment by guicho271828** [comment]
Well to be honest I never use an isolated functionality myself lol

**Comment by guicho271828** [comment]
I added that because I thought that would be cool, but I ended up not using it often

**Comment by phoe** [comment]
OK - I guessed as much. Still, I don't think the changes I'm making are backwards compatible enough to merge them here; I'll post here once I'm done and then we can figure out if and what can be backported here.

**Comment by guicho271828** [comment]
The latter one which deal with the hash tables would  the cause problems

**Comment by phoe** [comment]
A workaround would be to define symbol macros with the same names that expand into `(namespace-binding-table (symbol-namespace 'foo))`.

**Pull request closed without merging**
